TOKEN = 'DISCORD_TOKEN_HERE'

COGS_FOLDER = "./cogs"
COMMAND_PREFIX = "!"

LAVALINK_LOCAL = False
LAVALINK_HOST = "HOST_DOT_COM" #"127.0.0.1"
LAVALINK_PORT = "PORT_NUMBER" #2333
LAVALINK_PASSWORD = "PASSWORD" #'youshallnotpass'
LAVALINK_FILE_PATH = "Lavalink.jar"
LAVALINK_APPLICATION_FILE_PATH = "application.yml"

NOTIFICATION_EXPIRATION_TIME = 5
SEARCH_SONG_ITEMS_PER_PAGE = 10
