server:
  port: 2333
  address: 127.0.0.1
  http2:
    enabled: false
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true 
    clients:
      - MUSIC
      - ANDROID_TESTSUITE
      - WEB
      - TVHTML5EMBEDDED    
    WEB:
      playback: false
    TVHTML5EMBEDDED:
      playlistLoading: false
      videoLoading: false
      searching: false
lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.7.2"
      snapshot: false
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400 
    frameBufferDurationMs: 5000 
    opusEncodingQuality: 10
    resamplingQuality: LOW 
    trackStuckThresholdMs: 10000 
    useSeekGhosting: true 
    youtubePlaylistLoadLimit: 6 
    playerUpdateInterval: 5 
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO

  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000


  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
